#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoCao_MonHoc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLy_DienThoai")]
	public partial class DataQLDTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbangcap(bangcap instance);
    partial void Updatebangcap(bangcap instance);
    partial void Deletebangcap(bangcap instance);
    partial void Insertdienthoai(dienthoai instance);
    partial void Updatedienthoai(dienthoai instance);
    partial void Deletedienthoai(dienthoai instance);
    partial void Inserthangsanxuat(hangsanxuat instance);
    partial void Updatehangsanxuat(hangsanxuat instance);
    partial void Deletehangsanxuat(hangsanxuat instance);
    partial void Inserthoadon(hoadon instance);
    partial void Updatehoadon(hoadon instance);
    partial void Deletehoadon(hoadon instance);
    partial void Insertnhacungcap(nhacungcap instance);
    partial void Updatenhacungcap(nhacungcap instance);
    partial void Deletenhacungcap(nhacungcap instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Insertphieunhap(phieunhap instance);
    partial void Updatephieunhap(phieunhap instance);
    partial void Deletephieunhap(phieunhap instance);
    partial void InsertTKQUANTRI(TKQUANTRI instance);
    partial void UpdateTKQUANTRI(TKQUANTRI instance);
    partial void DeleteTKQUANTRI(TKQUANTRI instance);
    #endregion
		
		public DataQLDTDataContext() : 
				base(global::BaoCao_MonHoc.Properties.Settings.Default.QuanLy_DienThoaiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLDTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLDTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLDTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLDTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bangcap> bangcaps
		{
			get
			{
				return this.GetTable<bangcap>();
			}
		}
		
		public System.Data.Linq.Table<chitietpn> chitietpns
		{
			get
			{
				return this.GetTable<chitietpn>();
			}
		}
		
		public System.Data.Linq.Table<chitiethd> chitiethds
		{
			get
			{
				return this.GetTable<chitiethd>();
			}
		}
		
		public System.Data.Linq.Table<dienthoai> dienthoais
		{
			get
			{
				return this.GetTable<dienthoai>();
			}
		}
		
		public System.Data.Linq.Table<hangsanxuat> hangsanxuats
		{
			get
			{
				return this.GetTable<hangsanxuat>();
			}
		}
		
		public System.Data.Linq.Table<hoadon> hoadons
		{
			get
			{
				return this.GetTable<hoadon>();
			}
		}
		
		public System.Data.Linq.Table<nhacungcap> nhacungcaps
		{
			get
			{
				return this.GetTable<nhacungcap>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<phieunhap> phieunhaps
		{
			get
			{
				return this.GetTable<phieunhap>();
			}
		}
		
		public System.Data.Linq.Table<TKQUANTRI> TKQUANTRIs
		{
			get
			{
				return this.GetTable<TKQUANTRI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bangcap")]
	public partial class bangcap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mabc;
		
		private string _tenbc;
		
		private EntitySet<nhanvien> _nhanviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmabcChanging(string value);
    partial void OnmabcChanged();
    partial void OntenbcChanging(string value);
    partial void OntenbcChanged();
    #endregion
		
		public bangcap()
		{
			this._nhanviens = new EntitySet<nhanvien>(new Action<nhanvien>(this.attach_nhanviens), new Action<nhanvien>(this.detach_nhanviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabc", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mabc
		{
			get
			{
				return this._mabc;
			}
			set
			{
				if ((this._mabc != value))
				{
					this.OnmabcChanging(value);
					this.SendPropertyChanging();
					this._mabc = value;
					this.SendPropertyChanged("mabc");
					this.OnmabcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenbc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenbc
		{
			get
			{
				return this._tenbc;
			}
			set
			{
				if ((this._tenbc != value))
				{
					this.OntenbcChanging(value);
					this.SendPropertyChanging();
					this._tenbc = value;
					this.SendPropertyChanged("tenbc");
					this.OntenbcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bangcap_nhanvien", Storage="_nhanviens", ThisKey="mabc", OtherKey="mabc")]
		public EntitySet<nhanvien> nhanviens
		{
			get
			{
				return this._nhanviens;
			}
			set
			{
				this._nhanviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.bangcap = this;
		}
		
		private void detach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.bangcap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietpn")]
	public partial class chitietpn
	{
		
		private string _sopn;
		
		private string _madt;
		
		private System.DateTime _ngaydh;
		
		private int _soluong;
		
		private double _dongia;
		
		public chitietpn()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sopn", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string sopn
		{
			get
			{
				return this._sopn;
			}
			set
			{
				if ((this._sopn != value))
				{
					this._sopn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madt", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string madt
		{
			get
			{
				return this._madt;
			}
			set
			{
				if ((this._madt != value))
				{
					this._madt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydh", DbType="DateTime NOT NULL")]
		public System.DateTime ngaydh
		{
			get
			{
				return this._ngaydh;
			}
			set
			{
				if ((this._ngaydh != value))
				{
					this._ngaydh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this._soluong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="Float NOT NULL")]
		public double dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this._dongia = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitiethd")]
	public partial class chitiethd
	{
		
		private string _mahd;
		
		private string _madt;
		
		private System.DateTime _ngaydh;
		
		private int _soluong;
		
		private double _thanhtien;
		
		public chitiethd()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string mahd
		{
			get
			{
				return this._mahd;
			}
			set
			{
				if ((this._mahd != value))
				{
					this._mahd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madt", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string madt
		{
			get
			{
				return this._madt;
			}
			set
			{
				if ((this._madt != value))
				{
					this._madt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydh", DbType="DateTime NOT NULL")]
		public System.DateTime ngaydh
		{
			get
			{
				return this._ngaydh;
			}
			set
			{
				if ((this._ngaydh != value))
				{
					this._ngaydh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this._soluong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Float NOT NULL")]
		public double thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this._thanhtien = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dienthoai")]
	public partial class dienthoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madt;
		
		private string _tendt;
		
		private System.DateTime _ngaysx;
		
		private int _soluong;
		
		private double _gia;
		
		private string _kichthuoc;
		
		private int _trongluong;
		
		private string _mahsx;
		
		private EntityRef<hangsanxuat> _hangsanxuat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadtChanging(string value);
    partial void OnmadtChanged();
    partial void OntendtChanging(string value);
    partial void OntendtChanged();
    partial void OnngaysxChanging(System.DateTime value);
    partial void OnngaysxChanged();
    partial void OnsoluongChanging(int value);
    partial void OnsoluongChanged();
    partial void OngiaChanging(double value);
    partial void OngiaChanged();
    partial void OnkichthuocChanging(string value);
    partial void OnkichthuocChanged();
    partial void OntrongluongChanging(int value);
    partial void OntrongluongChanged();
    partial void OnmahsxChanging(string value);
    partial void OnmahsxChanged();
    #endregion
		
		public dienthoai()
		{
			this._hangsanxuat = default(EntityRef<hangsanxuat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madt", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madt
		{
			get
			{
				return this._madt;
			}
			set
			{
				if ((this._madt != value))
				{
					this.OnmadtChanging(value);
					this.SendPropertyChanging();
					this._madt = value;
					this.SendPropertyChanged("madt");
					this.OnmadtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendt", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tendt
		{
			get
			{
				return this._tendt;
			}
			set
			{
				if ((this._tendt != value))
				{
					this.OntendtChanging(value);
					this.SendPropertyChanging();
					this._tendt = value;
					this.SendPropertyChanged("tendt");
					this.OntendtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysx", DbType="Date NOT NULL")]
		public System.DateTime ngaysx
		{
			get
			{
				return this._ngaysx;
			}
			set
			{
				if ((this._ngaysx != value))
				{
					this.OnngaysxChanging(value);
					this.SendPropertyChanging();
					this._ngaysx = value;
					this.SendPropertyChanged("ngaysx");
					this.OnngaysxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Float NOT NULL")]
		public double gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kichthuoc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string kichthuoc
		{
			get
			{
				return this._kichthuoc;
			}
			set
			{
				if ((this._kichthuoc != value))
				{
					this.OnkichthuocChanging(value);
					this.SendPropertyChanging();
					this._kichthuoc = value;
					this.SendPropertyChanged("kichthuoc");
					this.OnkichthuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trongluong", DbType="Int NOT NULL")]
		public int trongluong
		{
			get
			{
				return this._trongluong;
			}
			set
			{
				if ((this._trongluong != value))
				{
					this.OntrongluongChanging(value);
					this.SendPropertyChanging();
					this._trongluong = value;
					this.SendPropertyChanged("trongluong");
					this.OntrongluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahsx", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string mahsx
		{
			get
			{
				return this._mahsx;
			}
			set
			{
				if ((this._mahsx != value))
				{
					if (this._hangsanxuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmahsxChanging(value);
					this.SendPropertyChanging();
					this._mahsx = value;
					this.SendPropertyChanged("mahsx");
					this.OnmahsxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hangsanxuat_dienthoai", Storage="_hangsanxuat", ThisKey="mahsx", OtherKey="mahsx", IsForeignKey=true)]
		public hangsanxuat hangsanxuat
		{
			get
			{
				return this._hangsanxuat.Entity;
			}
			set
			{
				hangsanxuat previousValue = this._hangsanxuat.Entity;
				if (((previousValue != value) 
							|| (this._hangsanxuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hangsanxuat.Entity = null;
						previousValue.dienthoais.Remove(this);
					}
					this._hangsanxuat.Entity = value;
					if ((value != null))
					{
						value.dienthoais.Add(this);
						this._mahsx = value.mahsx;
					}
					else
					{
						this._mahsx = default(string);
					}
					this.SendPropertyChanged("hangsanxuat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hangsanxuat")]
	public partial class hangsanxuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mahsx;
		
		private string _tenhsx;
		
		private string _diachi;
		
		private EntitySet<dienthoai> _dienthoais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahsxChanging(string value);
    partial void OnmahsxChanged();
    partial void OntenhsxChanging(string value);
    partial void OntenhsxChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public hangsanxuat()
		{
			this._dienthoais = new EntitySet<dienthoai>(new Action<dienthoai>(this.attach_dienthoais), new Action<dienthoai>(this.detach_dienthoais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahsx", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahsx
		{
			get
			{
				return this._mahsx;
			}
			set
			{
				if ((this._mahsx != value))
				{
					this.OnmahsxChanging(value);
					this.SendPropertyChanging();
					this._mahsx = value;
					this.SendPropertyChanged("mahsx");
					this.OnmahsxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenhsx", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenhsx
		{
			get
			{
				return this._tenhsx;
			}
			set
			{
				if ((this._tenhsx != value))
				{
					this.OntenhsxChanging(value);
					this.SendPropertyChanging();
					this._tenhsx = value;
					this.SendPropertyChanged("tenhsx");
					this.OntenhsxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hangsanxuat_dienthoai", Storage="_dienthoais", ThisKey="mahsx", OtherKey="mahsx")]
		public EntitySet<dienthoai> dienthoais
		{
			get
			{
				return this._dienthoais;
			}
			set
			{
				this._dienthoais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dienthoais(dienthoai entity)
		{
			this.SendPropertyChanging();
			entity.hangsanxuat = this;
		}
		
		private void detach_dienthoais(dienthoai entity)
		{
			this.SendPropertyChanging();
			entity.hangsanxuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadon")]
	public partial class hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mahd;
		
		private System.DateTime _ngaylap;
		
		private System.DateTime _ngayxuat;
		
		private double _tongtien;
		
		private string _manv;
		
		private string _makh;
		
		private EntityRef<khachhang> _khachhang;
		
		private EntityRef<nhanvien> _nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahdChanging(string value);
    partial void OnmahdChanged();
    partial void OnngaylapChanging(System.DateTime value);
    partial void OnngaylapChanged();
    partial void OnngayxuatChanging(System.DateTime value);
    partial void OnngayxuatChanged();
    partial void OntongtienChanging(double value);
    partial void OntongtienChanged();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    #endregion
		
		public hoadon()
		{
			this._khachhang = default(EntityRef<khachhang>);
			this._nhanvien = default(EntityRef<nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahd
		{
			get
			{
				return this._mahd;
			}
			set
			{
				if ((this._mahd != value))
				{
					this.OnmahdChanging(value);
					this.SendPropertyChanging();
					this._mahd = value;
					this.SendPropertyChanged("mahd");
					this.OnmahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylap", DbType="Date NOT NULL")]
		public System.DateTime ngaylap
		{
			get
			{
				return this._ngaylap;
			}
			set
			{
				if ((this._ngaylap != value))
				{
					this.OnngaylapChanging(value);
					this.SendPropertyChanging();
					this._ngaylap = value;
					this.SendPropertyChanged("ngaylap");
					this.OnngaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayxuat", DbType="DateTime NOT NULL")]
		public System.DateTime ngayxuat
		{
			get
			{
				return this._ngayxuat;
			}
			set
			{
				if ((this._ngayxuat != value))
				{
					this.OnngayxuatChanging(value);
					this.SendPropertyChanging();
					this._ngayxuat = value;
					this.SendPropertyChanged("ngayxuat");
					this.OnngayxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Float NOT NULL")]
		public double tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_hoadon", Storage="_khachhang", ThisKey="makh", OtherKey="makh", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._makh = value.makh;
					}
					else
					{
						this._makh = default(string);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_hoadon", Storage="_nhanvien", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhacungcap")]
	public partial class nhacungcap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mancc;
		
		private string _tenncc;
		
		private string _diachi;
		
		private string _sodt;
		
		private EntitySet<phieunhap> _phieunhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanccChanging(string value);
    partial void OnmanccChanged();
    partial void OntennccChanging(string value);
    partial void OntennccChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsodtChanging(string value);
    partial void OnsodtChanged();
    #endregion
		
		public nhacungcap()
		{
			this._phieunhaps = new EntitySet<phieunhap>(new Action<phieunhap>(this.attach_phieunhaps), new Action<phieunhap>(this.detach_phieunhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mancc", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mancc
		{
			get
			{
				return this._mancc;
			}
			set
			{
				if ((this._mancc != value))
				{
					this.OnmanccChanging(value);
					this.SendPropertyChanging();
					this._mancc = value;
					this.SendPropertyChanged("mancc");
					this.OnmanccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenncc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenncc
		{
			get
			{
				return this._tenncc;
			}
			set
			{
				if ((this._tenncc != value))
				{
					this.OntennccChanging(value);
					this.SendPropertyChanging();
					this._tenncc = value;
					this.SendPropertyChanged("tenncc");
					this.OntennccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodt", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string sodt
		{
			get
			{
				return this._sodt;
			}
			set
			{
				if ((this._sodt != value))
				{
					this.OnsodtChanging(value);
					this.SendPropertyChanging();
					this._sodt = value;
					this.SendPropertyChanged("sodt");
					this.OnsodtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhacungcap_phieunhap", Storage="_phieunhaps", ThisKey="mancc", OtherKey="mancc")]
		public EntitySet<phieunhap> phieunhaps
		{
			get
			{
				return this._phieunhaps;
			}
			set
			{
				this._phieunhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhacungcap = this;
		}
		
		private void detach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhacungcap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makh;
		
		private string _hoten;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private string _diachi;
		
		private string _sodt;
		
		private string _cccd;
		
		private EntitySet<hoadon> _hoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(System.DateTime value);
    partial void OnngaysinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsodtChanging(string value);
    partial void OnsodtChanged();
    partial void OncccdChanging(string value);
    partial void OncccdChanged();
    #endregion
		
		public khachhang()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="DateTime NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodt", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string sodt
		{
			get
			{
				return this._sodt;
			}
			set
			{
				if ((this._sodt != value))
				{
					this.OnsodtChanging(value);
					this.SendPropertyChanging();
					this._sodt = value;
					this.SendPropertyChanged("sodt");
					this.OnsodtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cccd", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string cccd
		{
			get
			{
				return this._cccd;
			}
			set
			{
				if ((this._cccd != value))
				{
					this.OncccdChanging(value);
					this.SendPropertyChanging();
					this._cccd = value;
					this.SendPropertyChanged("cccd");
					this.OncccdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_hoadon", Storage="_hoadons", ThisKey="makh", OtherKey="makh")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manv;
		
		private string _hotennv;
		
		private string _gioitinh;
		
		private string _quequan;
		
		private System.DateTime _ngaysinh;
		
		private System.DateTime _ngayvaolam;
		
		private string _cccd;
		
		private string _mabc;
		
		private EntitySet<hoadon> _hoadons;
		
		private EntitySet<phieunhap> _phieunhaps;
		
		private EntityRef<bangcap> _bangcap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnhotennvChanging(string value);
    partial void OnhotennvChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnquequanChanging(string value);
    partial void OnquequanChanged();
    partial void OnngaysinhChanging(System.DateTime value);
    partial void OnngaysinhChanged();
    partial void OnngayvaolamChanging(System.DateTime value);
    partial void OnngayvaolamChanged();
    partial void OncccdChanging(string value);
    partial void OncccdChanged();
    partial void OnmabcChanging(string value);
    partial void OnmabcChanged();
    #endregion
		
		public nhanvien()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			this._phieunhaps = new EntitySet<phieunhap>(new Action<phieunhap>(this.attach_phieunhaps), new Action<phieunhap>(this.detach_phieunhaps));
			this._bangcap = default(EntityRef<bangcap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hotennv", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string hotennv
		{
			get
			{
				return this._hotennv;
			}
			set
			{
				if ((this._hotennv != value))
				{
					this.OnhotennvChanging(value);
					this.SendPropertyChanging();
					this._hotennv = value;
					this.SendPropertyChanged("hotennv");
					this.OnhotennvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quequan", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string quequan
		{
			get
			{
				return this._quequan;
			}
			set
			{
				if ((this._quequan != value))
				{
					this.OnquequanChanging(value);
					this.SendPropertyChanging();
					this._quequan = value;
					this.SendPropertyChanged("quequan");
					this.OnquequanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayvaolam", DbType="Date NOT NULL")]
		public System.DateTime ngayvaolam
		{
			get
			{
				return this._ngayvaolam;
			}
			set
			{
				if ((this._ngayvaolam != value))
				{
					this.OnngayvaolamChanging(value);
					this.SendPropertyChanging();
					this._ngayvaolam = value;
					this.SendPropertyChanged("ngayvaolam");
					this.OnngayvaolamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cccd", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string cccd
		{
			get
			{
				return this._cccd;
			}
			set
			{
				if ((this._cccd != value))
				{
					this.OncccdChanging(value);
					this.SendPropertyChanging();
					this._cccd = value;
					this.SendPropertyChanged("cccd");
					this.OncccdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabc", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string mabc
		{
			get
			{
				return this._mabc;
			}
			set
			{
				if ((this._mabc != value))
				{
					if (this._bangcap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmabcChanging(value);
					this.SendPropertyChanging();
					this._mabc = value;
					this.SendPropertyChanged("mabc");
					this.OnmabcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_hoadon", Storage="_hoadons", ThisKey="manv", OtherKey="manv")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_phieunhap", Storage="_phieunhaps", ThisKey="manv", OtherKey="manv")]
		public EntitySet<phieunhap> phieunhaps
		{
			get
			{
				return this._phieunhaps;
			}
			set
			{
				this._phieunhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bangcap_nhanvien", Storage="_bangcap", ThisKey="mabc", OtherKey="mabc", IsForeignKey=true)]
		public bangcap bangcap
		{
			get
			{
				return this._bangcap.Entity;
			}
			set
			{
				bangcap previousValue = this._bangcap.Entity;
				if (((previousValue != value) 
							|| (this._bangcap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bangcap.Entity = null;
						previousValue.nhanviens.Remove(this);
					}
					this._bangcap.Entity = value;
					if ((value != null))
					{
						value.nhanviens.Add(this);
						this._mabc = value.mabc;
					}
					else
					{
						this._mabc = default(string);
					}
					this.SendPropertyChanged("bangcap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
		
		private void attach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieunhap")]
	public partial class phieunhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sopn;
		
		private System.DateTime _ngaynhap;
		
		private double _tonggia;
		
		private string _manv;
		
		private string _mancc;
		
		private EntityRef<nhacungcap> _nhacungcap;
		
		private EntityRef<nhanvien> _nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsopnChanging(string value);
    partial void OnsopnChanged();
    partial void OnngaynhapChanging(System.DateTime value);
    partial void OnngaynhapChanged();
    partial void OntonggiaChanging(double value);
    partial void OntonggiaChanged();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnmanccChanging(string value);
    partial void OnmanccChanged();
    #endregion
		
		public phieunhap()
		{
			this._nhacungcap = default(EntityRef<nhacungcap>);
			this._nhanvien = default(EntityRef<nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sopn", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sopn
		{
			get
			{
				return this._sopn;
			}
			set
			{
				if ((this._sopn != value))
				{
					this.OnsopnChanging(value);
					this.SendPropertyChanging();
					this._sopn = value;
					this.SendPropertyChanged("sopn");
					this.OnsopnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhap", DbType="DateTime NOT NULL")]
		public System.DateTime ngaynhap
		{
			get
			{
				return this._ngaynhap;
			}
			set
			{
				if ((this._ngaynhap != value))
				{
					this.OnngaynhapChanging(value);
					this.SendPropertyChanging();
					this._ngaynhap = value;
					this.SendPropertyChanged("ngaynhap");
					this.OnngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tonggia", DbType="Float NOT NULL")]
		public double tonggia
		{
			get
			{
				return this._tonggia;
			}
			set
			{
				if ((this._tonggia != value))
				{
					this.OntonggiaChanging(value);
					this.SendPropertyChanging();
					this._tonggia = value;
					this.SendPropertyChanged("tonggia");
					this.OntonggiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mancc", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string mancc
		{
			get
			{
				return this._mancc;
			}
			set
			{
				if ((this._mancc != value))
				{
					if (this._nhacungcap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanccChanging(value);
					this.SendPropertyChanging();
					this._mancc = value;
					this.SendPropertyChanged("mancc");
					this.OnmanccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhacungcap_phieunhap", Storage="_nhacungcap", ThisKey="mancc", OtherKey="mancc", IsForeignKey=true)]
		public nhacungcap nhacungcap
		{
			get
			{
				return this._nhacungcap.Entity;
			}
			set
			{
				nhacungcap previousValue = this._nhacungcap.Entity;
				if (((previousValue != value) 
							|| (this._nhacungcap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhacungcap.Entity = null;
						previousValue.phieunhaps.Remove(this);
					}
					this._nhacungcap.Entity = value;
					if ((value != null))
					{
						value.phieunhaps.Add(this);
						this._mancc = value.mancc;
					}
					else
					{
						this._mancc = default(string);
					}
					this.SendPropertyChanged("nhacungcap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_phieunhap", Storage="_nhanvien", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.phieunhaps.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.phieunhaps.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TKQUANTRI")]
	public partial class TKQUANTRI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    #endregion
		
		public TKQUANTRI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(255)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
